/**
 * JoRoScope: Malayalam (മലയാളം). The interface text (I18N.ml, keyed like the English and Tamil
 * dictionaries) and ML_TERMS, Malayalam for English astrological names and short labels, which
 * txt() and the page translator use wherever a text has no Malayalam of its own. Long readings
 * from the server stay in English until they are translated.
 * Loaded after i18n.js.
 */
I18N.ml = {
  "workspace": "പ്രവർത്തനമേഖല",
  "birth_chart": "ജാതകവും വർഗ്ഗങ്ങളും",
  "planets_strengths": "ഗ്രഹങ്ങളും ബലവും",
  "ashtakavarga": "അഷ്ടകവർഗ്ഗം",
  "yogas_doshas": "യോഗങ്ങളും ദോഷങ്ങളും",
  "vimshottari_dasa": "വിംശോത്തരി ദശ",
  "life_readings": "ജീവിത ഫലങ്ങൾ",
  "matching": "ജാതക പൊരുത്തം",
  "daily_panchangam": "ദൈനംദിന പഞ്ചാംഗം",
  "saved_profiles": "സൂക്ഷിച്ച ജാതകങ്ങൾ",
  "local_engine": "സ്വിസ് എഫെമെറിസ് (ലോക്കൽ)",
  "private_data": "ക്ലൗഡ് ട്രാക്കിംഗ് ഇല്ല · 100% സ്വകാര്യം",
  "my_location": "എന്റെ സ്ഥലം",
  "print_pdf": "പ്രിന്റ് / PDF",
  "birth_details": "ജനന വിവരങ്ങൾ",
  "enter_natal": "ജനന സമയവും സ്ഥലവും നൽകുക",
  "full_name": "പൂർണ്ണ നാമം",
  "birth_date": "തീയതി",
  "birth_time": "സമയം (24 മണിക്കൂർ)",
  "birthplace": "ജനന സ്ഥലം",
  "latitude": "അക്ഷാംശം (°N/S)",
  "longitude": "രേഖാംശം (°E/W)",
  "timezone": "IANA സമയമേഖല",
  "ayanamsa": "അയനാംശം",
  "dasa_year": "ദശാ വർഷം",
  "dasa_year_julian": "365.25 ദിവസം (ദക്ഷിണേന്ത്യൻ പഞ്ചാംഗങ്ങൾ)",
  "dasa_year_sidereal": "365.2564 ദിവസം (നാക്ഷത്ര വർഷം, ജഗന്നാഥ ഹോര)",
  "dasa_year_savana": "360 ദിവസം (സാവന വർഷം, പാരമ്പര്യം)",
  "dst_clock": "ക്ലോക്ക് ഫോൾഡ് (DST)",
  "generate_chart": "ജാതകം തയ്യാറാക്കുക",
  "ready_to_reveal": "ആകാശം വെളിപ്പെടുത്താൻ തയ്യാർ",
  "enter_details_prompt": "ജനന വിവരങ്ങൾ നൽകി ജാതകം തയ്യാറാക്കുക അമർത്തുക: ദക്ഷിണേന്ത്യൻ, ഉത്തരേന്ത്യൻ ചക്രങ്ങളും 16 വർഗ്ഗ ചക്രങ്ങളും ആഴത്തിലുള്ള ഗ്രഹ വിശകലനവും കാണാം.",
  "save_profile": "ജാതകം സൂക്ഷിക്കുക",
  "export_pdf": "PDF ആയി സേവ് ചെയ്യുക",
  "ascendant": "ലഗ്നം",
  "moon_sign": "കൂറ് (ചന്ദ്ര രാശി)",
  "birth_star": "ജന്മ നക്ഷത്രം",
  "active_dasa": "ഇന്നത്തെ ദശ",
  "south_indian": "ദക്ഷിണേന്ത്യൻ",
  "north_diamond": "ഉത്തരേന്ത്യൻ (വജ്രം)",
  "east_indian": "കിഴക്കേ ഇന്ത്യൻ",
  "sri_lankan": "ശ്രീലങ്കൻ",
  "click_house": "ഏതെങ്കിലും ഭാവം തിരഞ്ഞെടുക്കുക",
  "occupant_planets": "ഭാവത്തിലെ ഗ്രഹങ്ങൾ",
  "aspects_received": "ലഭിക്കുന്ന ദൃഷ്ടികൾ",
  "ashtakavarga_sav": "സർവ്വാഷ്ടകവർഗ്ഗ ബിന്ദുക്കൾ",
  "house_significations": "ഭാവ കാരകത്വങ്ങൾ",
  "astronomical_engine": "ഗണിത രീതി",
  "julian_day": "ജൂലിയൻ ദിനം",
  "ayanamsa_value": "അയനാംശ മൂല്യം",
  "graha": "ഗ്രഹം",
  "sign": "രാശി",
  "degrees": "ഡിഗ്രി",
  "star_pada": "നക്ഷത്രം / പാദം",
  "house": "ഭാവം",
  "dignity": "ബലസ്ഥിതി",
  "motion_status": "സ്ഥിതി",
  "aspects_cast": "നൽകുന്ന ദൃഷ്ടി (ഭാവങ്ങൾ)",
  "sav_title": "സർവ്വാഷ്ടകവർഗ്ഗ (SAV) ബിന്ദുക്കൾ",
  "bav_title": "ഭിന്നാഷ്ടകവർഗ്ഗ (BAV) പട്ടിക",
  "sodhana_title": "ശോധിത അഷ്ടകവർഗ്ഗവും ശോധ്യ പിണ്ഡവും",
  "sodhana_sub": "ത്രികോണ, ഏകാധിപത്യ ശോധനകൾക്ക് ശേഷമുള്ള ബിന്ദുക്കളും, ആയുസ്സിനും ഗോചാര സമയനിർണ്ണയത്തിനും ഉപയോഗിക്കുന്ന രാശി, ഗ്രഹ, ശോധ്യ പിണ്ഡങ്ങളും.",
  "detected_yogas": "ജാതകത്തിലെ യോഗങ്ങൾ",
  "current_running_period": "ഇന്ന് നടക്കുന്ന ദശാകാലം",
  "lagna_path": "ലഗ്നവും ജീവിതപാതയും",
  "moon_mind": "ചന്ദ്രനും മനസ്സും",
  "sun_vitality": "സൂര്യനും ആത്മലക്ഷ്യവും",
  "career_karma": "തൊഴിലും പത്താം ഭാവവും",
  "wealth_gains": "ധനവും സാമ്പത്തിക ഭാഗ്യവും",
  "relationships_7th": "വിവാഹവും പങ്കാളിത്തവും",
  "active_dasa_focus": "നടപ്പുദശയുടെ ശ്രദ്ധാകേന്ദ്രം",
  "tithi": "തിഥി",
  "nakshatra": "നക്ഷത്രം",
  "nitya_yoga": "നിത്യയോഗം",
  "karana": "കരണം",
  "export_json": "JSON ബാക്കപ്പ് എടുക്കുക",
  "import_json": "JSON ബാക്കപ്പ് ചേർക്കുക",
  "save_person": "സൂക്ഷിക്കുക",
  "new_person": "പുതിയ വ്യക്തി",
  "clear_all": "എല്ലാം മായ്ക്കുക",
  "load_saved_profile": "സൂക്ഷിച്ച വ്യക്തിയെ തിരഞ്ഞെടുക്കുക",
  "quick_load_person": "👤 -- വ്യക്തിയെ തിരഞ്ഞെടുക്കുക --",
  "timeline_predictions_mode": "കാലക്രമ ഫലങ്ങൾ",
  "tabular_cycles_mode": "ദശാ പട്ടിക (3 തലങ്ങൾ)",
  "live_active_period": "ഇന്ന് നടക്കുന്ന ജീവിതകാലം",
  "running_dates": "തീയതികളും കാലയളവും",
  "current_age": "ഇപ്പോഴത്തെ പ്രായം",
  "elapsed_time": "കഴിഞ്ഞ ദിവസങ്ങൾ",
  "remaining_time": "ബാക്കി ദിവസങ്ങൾ",
  "strategic_focus": "കാലത്തിന്റെ ശ്രദ്ധയും സമീപനവും",
  "primary_remedy": "നിർദ്ദേശിച്ച പരിഹാരവും മന്ത്രവും",
  "filter_active": "ഇന്ന് നടക്കുന്നത്",
  "filter_next5": "അടുത്ത 5 വർഷം",
  "filter_annual": "വാർഷിക നാഴികക്കല്ലുകൾ",
  "filter_all": "മുഴുവൻ ജീവിതം (81 കാലങ്ങൾ)",
  "filter_auspicious": "ശുഭകാലങ്ങൾ (3+ ★)",
  "filter_caution": "ശ്രദ്ധിക്കേണ്ട കാലങ്ങൾ",
  "filter_by_lord": "മഹാദശാനാഥൻ:",
  "jump": "പോകുക",
  "annual_projections_title": "10 വർഷത്തെ വാർഷിക പ്രവചനം",
  "annual_projections_sub": "ഈ കാലഘട്ടത്തിലെ നാഴികക്കല്ലുകളും ജ്യോതിഷ അനുകൂലതാ സ്കോറും",
  "open_timeline_studio": "81 കാലങ്ങളുടെ കാലരേഖ തുറക്കുക →",
  "city_helper": "സ്ഥലം തിരയുക അല്ലെങ്കിൽ താഴെ അക്ഷാംശ-രേഖാംശങ്ങൾ നൽകുക.",
  "print_jathagam": "ജാതകം പ്രിന്റ് ചെയ്യുക",
  "title_print_jathagam": "പരമ്പരാഗത ജാതകം പ്രിന്റ് ചെയ്യുക: ജനനക്കുറിപ്പ്, രാശി, നവാംശം, ഗ്രഹങ്ങൾ, ദശാ-അപഹാരം",
  "bhava_col": "ഭാവം (ശ്രീപതി)",
  "gowri_title": "ഗൗരി പഞ്ചാംഗം (നല്ല നേരം)",
  "gowri_sub": "അമൃതം, ഉതി, ലാഭം, ധനം, സുഖം നല്ല സമയങ്ങൾ; രോഗം, ശോരം, വിഷം ഒഴിവാക്കുക.",
  "saturn_cycles_title": "ജീവിതത്തിലെ ശനി ചക്രങ്ങൾ",
  "saturn_cycles_sub": "ഏഴര ശനി (കണ്ടകശനി ഉൾപ്പെടെ), അർദ്ധാഷ്ടമ, കണ്ടക, അഷ്ടമ ശനി: കൂറിൽ നിന്ന് എണ്ണി, ആദ്യ പ്രവേശനം മുതൽ അവസാന പുറത്തുപോക്ക് വരെ.",
  "th_cycle": "ചക്രം",
  "th_period": "കാലയളവ്",
  "th_age": "പ്രായം",
  "th_phases": "ഘട്ടങ്ങൾ",
  "print_porutham": "പൊരുത്തം റിപ്പോർട്ട് പ്രിന്റ് ചെയ്യുക",
  "title_print_porutham": "പൊരുത്ത റിപ്പോർട്ട് പ്രിന്റ് ചെയ്യുക",
  "upagrahas_title": "ഉപഗ്രഹങ്ങൾ",
  "upagrahas_sub": "കാലൻ, മൃത്യു, അർത്ഥപ്രഹരൻ, യമഘണ്ടകൻ എന്നിവ പകലിന്റെയോ രാത്രിയുടെയോ അവയുടെ അധിപന്റെ ഭാഗത്തിന്റെ മധ്യത്തിൽ ഉദിക്കുന്നു, ഗുളികൻ ശനിയുടെ ഭാഗത്തിന്റെ തുടക്കത്തിൽ; ധൂമാദി ഗണം സൂര്യനിൽ നിന്ന്.",
  "th_upagraha": "ഉപഗ്രഹം",
  "yogini_mode": "യോഗിനി ദശ",
  "yogini_title": "യോഗിനി ദശ (36 വർഷ ചക്രം)",
  "yogini_sub": "ചന്ദ്രൻ, സൂര്യൻ, വ്യാഴം, ചൊവ്വ, ബുധൻ, ശനി, ശുക്രൻ, രാഹു എന്നിവർ ഭരിക്കുന്ന എട്ട് യോഗിനികൾ; ജന്മനക്ഷത്രം ആദ്യത്തേത് നിശ്ചയിക്കുന്നു.",
  "ashtottari_mode": "അഷ്ടോത്തരി ദശ",
  "ashtottari_title": "അഷ്ടോത്തരി ദശ (108 വർഷ ചക്രം)",
  "ashtottari_sub": "തിരുവാതിര മുതൽ എണ്ണുന്ന ജന്മനക്ഷത്ര ഗണപ്രകാരം എട്ട് നാഥന്മാർ (കേതു ഇല്ല); ഓരോ ദശയിലും സ്വന്തം നാഥനിൽ തുടങ്ങുന്ന എട്ട് അപഹാരങ്ങൾ.",
  "chara_mode": "ചര ദശ",
  "chara_title": "ജൈമിനി ചര ദശ (കെ.എൻ. റാവു)",
  "chara_sub": "ലഗ്നത്തിൽ നിന്നുള്ള രാശി ദശകൾ, ഒൻപതാം രാശി ഓജപാദമെങ്കിൽ മുന്നോട്ട്; ഓരോ രാശിയുടെയും കാലം അതിന്റെ നാഥനിലേക്കുള്ള ദൂരം. പന്ത്രണ്ട് അന്തർദശകൾ അടുത്ത രാശിയിൽ തുടങ്ങി ദശാരാശിയിൽ അവസാനിക്കുന്നു.",
  "month_cal_title": "മാസ കലണ്ടർ",
  "month_cal_sub": "സൂര്യോദയത്തിലെ തിഥിയും നക്ഷത്രവും, അമാവാസി, പൗർണ്ണമി, ഏകാദശി, പ്രദോഷം, ഷഷ്ഠി, സങ്കടഹര ചതുർത്ഥി, മാസശിവരാത്രി, കാർത്തിക എന്നിവയോടെ.",
  "rasi_navamsa": "രാശി + നവാംശം",
  "jathaga_kurippu": "ജാതകക്കുറിപ്പ്",
  "jathaga_kurippu_sub": "പഞ്ചാംഗ പാരമ്പര്യത്തിലെ ജനനക്കുറിപ്പുകൾ",
  "badge_ja": "ജാ",
  "chevvai_dosham": "ചൊവ്വാ ദോഷം (കുജ ദോഷം)",
  "rahu_ketu_dosham": "രാഹു-കേതു ദോഷം (സർപ്പ ദോഷം)",
  "dosha_samyam": "ദോഷസാമ്യം (ചൊവ്വ, പാപ ബലം)",
  "dosha": "ദോഷം",
  "bride": "വധു",
  "groom": "വരൻ",
  "samyam": "സാമ്യം",
  "panch_date": "തീയതി",
  "panch_now": "ഇപ്പോൾ",
  "panch_location": "സ്ഥലം",
  "panch_location_hint": "ജനന ഫോമിൽ നിന്ന്. മാറ്റാൻ 📍 എന്റെ സ്ഥലം ഉപയോഗിക്കുക.",
  "tamil_calendar": "കലണ്ടർ (സൗരമാസം)",
  "soolam": "ശൂലം (യാത്ര ഒഴിവാക്കുക)",
  "tamil_yogam": "അമൃതാദി യോഗം",
  "chandrashtamam": "ചന്ദ്രാഷ്ടമം",
  "personal_balam": "നിങ്ങളുടെ ദിവസം: താരാബലവും ചന്ദ്രബലവും",
  "tara_balam": "താരാബലം",
  "chandra_balam": "ചന്ദ്രബലം",
  "five_limbs": "കാലത്തിന്റെ അഞ്ച് അംഗങ്ങൾ (പഞ്ചാംഗം)",
  "vaaram": "വാരം (ആഴ്ച ദിവസം)",
  "muhurtha_local": "മുഹൂർത്ത സമയങ്ങൾ (പ്രാദേശിക സമയം)",
  "sunrise_sunset": "സൂര്യോദയവും അസ്തമയവും",
  "abhijit": "അഭിജിത് മുഹൂർത്തം",
  "abhijit_sub": "പകലിലെ ഏറ്റവും ശുഭമായ സമയം",
  "rahu_kalam": "രാഹുകാലം",
  "rahu_kalam_sub": "രാഹു ഭരിക്കുന്ന അശുഭ കാലം",
  "yamagandam": "യമഗണ്ഡം",
  "yamagandam_sub": "യമൻ ഭരിക്കുന്ന അശുഭ കാലം",
  "kuligai": "ഗുളികകാലം",
  "kuligai_sub": "ശനിയുടെ ഭാഗം: ആവർത്തിക്കരുതാത്ത കാര്യങ്ങൾ തുടങ്ങരുത്",
  "peyarchi_title": "വരാനിരിക്കുന്ന രാശിമാറ്റങ്ങൾ",
  "peyarchi_date": "തീയതി",
  "peyarchi_from_to": "നിന്ന് → ലേക്ക്",
  "house_from_moon": "കൂറിൽ നിന്നുള്ള ഭാവം",
  "gochara_table_title": "ഇന്നത്തെ ഗോചാരം അഷ്ടകവർഗ്ഗത്തോടെ",
  "bindus": "ബിന്ദുക്കൾ",
  "transit_result": "ഫലം",
  "next_chandrashtamam": "അടുത്ത ചന്ദ്രാഷ്ടമം",
  "star_birthday": "പിറന്നാൾ (നക്ഷത്രപ്രകാരം)",
  "hora_title": "ഹോരാ സമയങ്ങൾ",
  "hora_sub": "സൂര്യോദയം മുതൽ പകലിലെ പന്ത്രണ്ടും രാത്രിയിലെ പന്ത്രണ്ടും ഹോരകൾ; ചന്ദ്രൻ, ബുധൻ, വ്യാഴം, ശുക്രൻ ഹോരകൾ ശുഭം.",
  "sacred_geometry": "ജ്യോതിശാസ്ത്ര കൃത്യതയും വൈദിക പാരമ്പര്യവും",
  "birth_chart_heading": "നിങ്ങളുടെ ഗ്രഹനില",
  "birth_chart_sub": "രാശി, നവാംശം, 16 പാരാശര വർഗ്ഗങ്ങൾ എന്നിവയിലെ ഗ്രഹസ്ഥിതികൾ കാണുക.",
  "planetary_status": "ഗ്രഹ അവസ്ഥകളും ദൃഷ്ടികളും",
  "planets_sub": "ഡിഗ്രി, നക്ഷത്ര പാദം, ബലസ്ഥിതി, മൗഢ്യം, വേഗം, വൈദിക ദൃഷ്ടികൾ.",
  "parashara_system": "പാരാശര അഷ്ടകവർഗ്ഗ രീതി",
  "ashtakavarga_sub": "സർവ്വാഷ്ടകവർഗ്ഗം (ആകെ 337 ബിന്ദുക്കൾ), 12 രാശികളിലെ ഭിന്നാഷ്ടകവർഗ്ഗ ബിന്ദുക്കൾ.",
  "karmic_combinations": "യോഗങ്ങളും ദോഷങ്ങളും",
  "yogas_sub": "പഞ്ചമഹാപുരുഷ, രാജ, ധന, വിപരീത യോഗങ്ങളും കുജ, കാളസർപ്പ ദോഷ വിശകലനവും സ്വയമേവ.",
  "planetary_cycles": "120 വർഷ വിംശോത്തരി ചക്രവും ജീവിത കാലരേഖയും",
  "dasa_sub": "9 മഹാദശകളിലൂടെയും 81 അപഹാരങ്ങളിലൂടെയും കാലക്രമ ജീവിത പ്രവചനം, ഗ്രഹ ബന്ധങ്ങൾ, 10 വർഷ വാർഷിക പ്രവചനം.",
  "astrological_synthesis": "സമഗ്ര ജാതക ഫല റിപ്പോർട്ട്",
  "predictions_sub": "പാരാശര, ദക്ഷിണേന്ത്യൻ ജ്യോതിഷ ഫലങ്ങൾ: നക്ഷത്രം, ലഗ്നം, 12 ഭാവങ്ങൾ, ഭാവങ്ങളിലെ ഗ്രഹങ്ങൾ, ദശാ-അപഹാരം, ഗോചാരം, ഭാഗ്യരത്നങ്ങൾ.",
  "marital_compatibility": "വിവാഹ പൊരുത്തം (10 പൊരുത്തങ്ങൾ)",
  "matching_sub": "ദക്ഷിണേന്ത്യൻ 10 പൊരുത്തങ്ങളും ഉത്തരേന്ത്യൻ 36 ഗുണ മിലനും കൃത്യമായി കണക്കാക്കുക.",
  "celestial_calendar": "നിത്യ പഞ്ചാംഗവും സമയങ്ങളും",
  "panchangam_sub": "കാലത്തിന്റെ അഞ്ച് ഘടകങ്ങൾ: തിഥി, വാരം, നക്ഷത്രം, യോഗം, കരണം, ശുഭ മുഹൂർത്തങ്ങളോടെ.",
  "browser_vault": "ബ്രൗസറിലെ സംഭരണം",
  "profiles_sub": "കുടുംബത്തിന്റെയും ഉപഭോക്താക്കളുടെയും ജാതകങ്ങൾ ഈ ബ്രൗസറിൽ സൂക്ഷിക്കുക. എപ്പോൾ വേണമെങ്കിലും ബാക്കപ്പ് എടുക്കാം.",
  "brand_sub": "വൈദിക ജാതകം",
  "engine_status": "സ്വിസ് എഫെമെറിസ് 2.10",
  "title_geo": "ഇപ്പോഴത്തെ GPS സ്ഥലം ഉപയോഗിക്കുക",
  "title_lang": "ഭാഷ മാറ്റുക",
  "title_theme": "ഇരുണ്ട/തെളിഞ്ഞ തീം മാറ്റുക",
  "title_print": "പ്രിന്റ് അല്ലെങ്കിൽ PDF",
  "title_quick_load": "സൂക്ഷിച്ച വ്യക്തിയെ തിരഞ്ഞെടുത്ത് ജാതകം ഉടൻ കണക്കാക്കുക",
  "title_save_person": "ഈ വ്യക്തിയുടെ വിവരങ്ങൾ സൂക്ഷിക്കുക",
  "title_new_person": "പുതിയ വ്യക്തിക്കായി ഫോം മായ്ക്കുക",
  "ph_name": "ഈ ജാതകത്തിന്റെ പേര്",
  "city_count": "5,481 നഗരങ്ങൾ",
  "ph_city": "നഗരത്തിന്റെ പേര് ടൈപ്പ് ചെയ്യുക (ഉദാ. കൊച്ചി, തിരുവനന്തപുരം, ചെന്നൈ)...",
  "ayan_lahiri": "ലാഹിരി (ചിത്രാപക്ഷം - സാധാരണ)",
  "ayan_raman": "ബി.വി. രാമൻ",
  "ayan_kp": "കെ.പി. (കൃഷ്ണമൂർത്തി)",
  "ayan_fagan": "ഫാഗൻ-ബ്രാഡ്ലി (പാശ്ചാത്യ നിരയന)",
  "fold_auto": "സ്വയമേവ",
  "fold_first": "ഒന്നാം തവണ (സാധാരണ)",
  "fold_second": "രണ്ടാം തവണ (ആവർത്തിച്ചത്)",
  "pill_vargas": "✦ 16 വർഗ്ഗ ചക്രങ്ങൾ",
  "pill_ashtaka": "✦ പാരാശര അഷ്ടകവർഗ്ഗം",
  "pill_dasa": "✦ 3 തല ദശ",
  "pill_yoga": "✦ യോഗ നിർണ്ണയം",
  "pill_porutham": "✦ 10 പൊരുത്തങ്ങൾ",
  "title_save_local": "ബ്രൗസറിൽ സൂക്ഷിക്കുക",
  "title_export_pdf": "PDF / പ്രിന്റ്",
  "legend_benefic": "ശുഭൻ",
  "legend_malefic": "പാപൻ",
  "legend_combust": "🔥 മൗഢ്യം",
  "click_house_rest": "ഭാവനാഥൻ, ഭാവത്തിലെ ഗ്രഹങ്ങൾ, ദൃഷ്ടികൾ, കാരകത്വങ്ങൾ കാണാൻ.",
  "sav_note": "28-ൽ കൂടുതൽ ബിന്ദുക്കളുള്ള ഭാവങ്ങൾ ബലവും എളുപ്പവും നൽകും; 28-ൽ കുറഞ്ഞവയ്ക്ക് ശ്രദ്ധ വേണം.",
  "sav_total": "ആകെ: 337 ബിന്ദുക്കൾ",
  "th_planet": "ഗ്രഹം",
  "kaal_sarp_title": "കാളസർപ്പ ദോഷം",
  "spotlight_calc_note": "സ്വിസ് എഫെമെറിസ് വിംശോത്തരി ശിഷ്ടപ്രകാരം",
  "tl_all": "🪐 എല്ലാ 9 മഹാദശകളും",
  "tl_sun": "☀️ സൂര്യൻ",
  "tl_moon": "🌙 ചന്ദ്രൻ",
  "tl_mars": "♂️ ചൊവ്വ",
  "tl_rahu": "☊ രാഹു",
  "tl_jupiter": "♃ വ്യാഴം",
  "tl_saturn": "♄ ശനി",
  "tl_mercury": "☿ ബുധൻ",
  "tl_ketu": "☋ കേതു",
  "tl_venus": "♀️ ശുക്രൻ",
  "ph_jump_year": "വർഷത്തിലേക്ക് പോകുക (ഉദാ. 2026)",
  "title_jump_year": "വർഷത്തിലേക്ക് പോകുക",
  "year_by_year": "വർഷം തോറുമുള്ള പ്രവചനം",
  "jump_active_dasa": "നടപ്പുദശയിലേക്ക് പോകുക",
  "pt_natal": "🌟 ജന്മഫലവും സ്വഭാവവും",
  "pt_parisodhanai": "🔎 ജാതക പരിശോധന",
  "pt_ask": "💬 ജാതകത്തെക്കുറിച്ച് ചോദിക്കുക",
  "pt_yearly": "📅 വർഷംതോറുമുള്ള ഫലം",
  "pt_education": "🎓 വിദ്യാഭ്യാസം",
  "pt_children": "👶 സന്താനം",
  "pt_health": "🩺 ആരോഗ്യം",
  "pt_wealth": "💰 സമ്പത്ത് & സ്വത്ത്",
  "pt_foreign": "✈️ വിദേശയാത്ര",
  "pt_spiritual": "🕉️ ആത്മീയ ജീവിതം",
  "pt_bhavas": "🏛️ 12 ഭാവങ്ങൾ",
  "pt_planets": "🪐 ഭാവങ്ങളിലെ ഗ്രഹങ്ങൾ",
  "pt_dasa": "⏳ ദശാ-അപഹാര ഫലം",
  "pt_transits": "🌌 ഗോചാരം",
  "pt_remedies": "💎 ഭാഗ്യരത്നങ്ങൾ",
  "pt_jaimini": "🪷 ജൈമിനി കാരകങ്ങൾ",
  "pt_timing": "⏱️ ഇരട്ട ഗോചാരം",
  "pt_career": "💼 ദശാംശം: തൊഴിൽ",
  "pt_ayur": "🌿 ആയുർ-ജ്യോതിഷം",
  "pt_kakshya": "📐 അഷ്ടകവർഗ്ഗ കക്ഷ്യകൾ",
  "pt_shadbala": "⚖️ ഷഡ്ബലം",
  "pt_kp": "🔍 കെ.പി. ഉപനാഥന്മാർ",
  "pt_bnn": "📜 ഭൃഗു നന്ദി നാഡി",
  "pt_avasthas": "✨ ഗ്രഹ അവസ്ഥകൾ",
  "pt_pada": "🎯 നക്ഷത്രപാദ ഫലം",
  "pt_sahams": "🔮 സഹമങ്ങൾ",
  "nav_tools": "പ്രശ്നവും ഉപകരണങ്ങളും",
  "tools_eyebrow": "പ്രശ്നവും ജനനസമയ ശുദ്ധീകരണവും",
  "tools_sub": "ഈ നിമിഷത്തെക്കുറിച്ച് ചോദ്യം ചോദിക്കുക, അല്ലെങ്കിൽ ജീവിത സംഭവങ്ങൾ ഉപയോഗിച്ച് ജനനസമയം പരിശോധിക്കുക.",
  "rect_title": "ജനനസമയ ശുദ്ധീകരണം",
  "rect_sub": "ജനനസമയം ഉറപ്പില്ലേ? ജീവിതത്തിലെ സംഭവങ്ങൾ തീയതിയോടെ ചേർക്കുക; ജനന ഫോമിലെ സമയത്തിനു ചുറ്റുമുള്ള സമയങ്ങൾ അവയുടെ ദശകളും ഗോചാരവും കൊണ്ട് പരിശോധിക്കും. അഞ്ചോ അതിലധികമോ സംഭവങ്ങൾ മികച്ച ഫലം നൽകും.",
  "rect_add": "➕ സംഭവം ചേർക്കുക",
  "rect_w30": "± 30 മിനിറ്റ്",
  "rect_w60": "± 1 മണിക്കൂർ",
  "rect_w120": "± 2 മണിക്കൂർ",
  "rect_run": "ജനനസമയങ്ങൾ പരിശോധിക്കുക",
  "prasna_title": "പ്രശ്നം",
  "prasna_sub": "നിങ്ങൾ ചോദിക്കുന്ന നിമിഷത്തിന്റെ ജാതകം, ജനന ഫോമിലെ സ്ഥലത്ത്, പ്രശ്നമാർഗ്ഗ, താജിക നിയമപ്രകാരം. വേണമെങ്കിൽ ചോദ്യം മനസ്സിൽ വിചാരിച്ച് 1 മുതൽ 12 വരെ ഒരു സംഖ്യ തിരഞ്ഞെടുക്കുക (ആരൂഢം).",
  "prasna_arudha": "ആരൂഢം 1-12",
  "prasna_ask": "ഇപ്പോൾ ചോദിക്കുക",
  "prasna_hint": "ഈ നിമിഷം ഉപയോഗിക്കാൻ തീയതിയും സമയവും ഒഴിച്ചിടുക.",
  "pt_numerology": "🔢 സംഖ്യാശാസ്ത്രം",
  "pt_chakras": "🔷 സർവ്വതോഭദ്ര, കോട്ട ചക്രം",
  "pt_marriage": "💞 വിവാഹ റിപ്പോർട്ട്",
  "pt_career_report": "📈 തൊഴിൽ റിപ്പോർട്ട്",
  "pt_varshaphal": "🎉 വർഷഫലം",
  "pt_monthly": "🗓️ മാസ ഗോചാരം",
  "pt_parihara": "🕉️ പരിഹാരങ്ങൾ",
  "ics_add": "📅 കലണ്ടറിൽ ചേർക്കുക",
  "ics_month": "📅 ഈ മാസത്തെ വ്രതങ്ങൾ കലണ്ടറിൽ ചേർക്കുക",
  "ics_muhurtham": "📅 ഈ മുഹൂർത്തങ്ങൾ കലണ്ടറിൽ ചേർക്കുക",
  "h_bhavas": "12 ഭാവങ്ങൾ: സമഗ്ര ജീവിതപാത",
  "pill_all_houses": "എല്ലാ 12 ഭാവങ്ങളും",
  "p_bhavas": "ഭാവനാഥന്റെ സ്ഥിതി, ഭാവത്തിലെ ഗ്രഹങ്ങൾ, ദൃഷ്ടികൾ, സർവ്വാഷ്ടകവർഗ്ഗ ബലം എന്നിവ അടിസ്ഥാനമാക്കിയ ഓരോ ഭാവത്തിന്റെയും ഫലം.",
  "h_planet_positions": "ഗ്രഹസ്ഥിതികളും സ്വാധീനവും",
  "pill_9_grahas": "9 ഗ്രഹങ്ങൾ",
  "p_planets": "സൂര്യൻ, ചന്ദ്രൻ, ചൊവ്വ, ബുധൻ, വ്യാഴം, ശുക്രൻ, ശനി, രാഹു, കേതു എന്നിവ ജന്മഭാവങ്ങളിൽ നൽകുന്ന ഫലങ്ങൾ.",
  "active_dasa_forecast": "നടപ്പുദശാ-അപഹാര ഫലം",
  "h_maha_dasas": "9 മഹാദശകളുടെ ജീവിത ചക്രങ്ങൾ",
  "pill_120_years": "120 വർഷം",
  "h_transits": "ഗ്രഹ ഗോചാരം",
  "pill_current_weather": "ഇപ്പോഴത്തെ ജ്യോതിഷ കാലാവസ്ഥ",
  "p_transits": "നിങ്ങളുടെ ജന്മരാശിയിൽ (കൂറിൽ) നിന്ന് കണക്കാക്കിയ ഗോചാര വിശകലനം.",
  "h_remedies": "ശുഭ ഘടകങ്ങൾ, ഭാഗ്യരത്നങ്ങൾ, പരിഹാരങ്ങൾ",
  "pill_guidance": "ജ്യോതിഷ മാർഗ്ഗനിർദ്ദേശം",
  "p_remedies": "നിങ്ങളുടെ ലഗ്നത്തിനായി കണക്കാക്കിയ രത്നങ്ങൾ, ശുഭ സംഖ്യകൾ, ദിവസങ്ങൾ, നിറങ്ങൾ, രക്ഷാദേവതകൾ.",
  "h_gems": "ശുപാർശ ചെയ്യുന്ന രത്നങ്ങൾ",
  "sub_gems": "ജീവരത്നവും ഭാഗ്യരത്നവും",
  "h_lucky": "ഭാഗ്യ സംഖ്യകൾ, ദിവസങ്ങൾ, നിറങ്ങൾ",
  "sub_lucky": "അനുകൂല ഗ്രഹസ്ഥിതികൾ",
  "pill_upadesha": "ഉപദേശ സൂത്രങ്ങൾ",
  "p_jaimini": "ഡിഗ്രി അടിസ്ഥാനമാക്കിയ ചര കാരകങ്ങൾ: ആത്മാവിന്റെ കർമ്മപരിണാമം (ആത്മകാരകൻ), തൊഴിൽ (അമാത്യകാരകൻ), ഗുരുക്കന്മാർ, അമ്മ, സന്താനം, വെല്ലുവിളികൾ, ജീവിതപങ്കാളി (ദാരകാരകൻ).",
  "soul_purpose": "ആത്മാവിന്റെ പരമലക്ഷ്യം (നവാംശത്തിലെ കാരകാംശം)",
  "p_double_transit": "അനുഭവസിദ്ധമായ നിയമം: ശനിയും (കർമ്മം) വ്യാഴവും (അനുഗ്രഹം) ഒരേസമയം ജന്മഭാവങ്ങളിൽ ദൃഷ്ടി ചെയ്യുമ്പോൾ മാത്രമേ പ്രധാന സംഭവങ്ങൾ നടക്കൂ.",
  "transit_saturn_today": "ഇന്നത്തെ ശനി ഗോചാരം",
  "transit_jupiter_today": "ഇന്നത്തെ വ്യാഴ ഗോചാരം",
  "h_career": "ദശാംശവും (D-10) തൊഴിൽ അഭിരുചിയും",
  "pill_bvb": "ഭാരതീയ വിദ്യാഭവൻ രീതി",
  "p_career": "വരാഹമിഹിരന്റെ കർമ്മജീവ നിയമം (ബൃഹജ്ജാതകം 10) ദശാംശത്തോടൊപ്പം; തൊഴിൽ ഭരിക്കുന്ന ഗ്രഹങ്ങളെ ആധാരമാക്കി 5 തൊഴിൽ വിഭാഗങ്ങൾക്ക് സ്കോർ.",
  "h_ayur": "ആയുർ-ജ്യോതിഷവും ത്രിദോഷ ആരോഗ്യവും",
  "pill_charaka": "ചരകനും പ്രശ്നമാർഗ്ഗവും",
  "p_ayur": "വാത, പിത്ത, കഫ സന്തുലനം, ദഹനപ്രവണത, അവയവബലം എന്നിവയുടെ ആയുർവേദ പ്രകൃതി വിശകലനം.",
  "prakriti": "ജന്മ പ്രകൃതി",
  "vata_label": "വാതം (വായു/ആകാശം)",
  "pitta_label": "പിത്തം (അഗ്നി)",
  "kapha_label": "കഫം (ജലം/ഭൂമി)",
  "h_vulnerabilities": "ശാരീരിക ദുർബലതകൾ",
  "sub_6th": "ആറാം ഭാവവും (രോഗഭാവം) ആറാം ഭാവാധിപനും",
  "h_lifestyle": "ആയുർവേദ പ്രതിരോധ ജീവിതശൈലി",
  "sub_lifestyle": "ആഹാര, യോഗ നിർദ്ദേശങ്ങൾ",
  "h_kakshya": "അഷ്ടകവർഗ്ഗ കക്ഷ്യ ഗോചാര രീതി",
  "pill_raman_patel": "ഡോ. ബി.വി. രാമൻ, സി.എസ്. പട്ടേൽ",
  "p_kakshya": "ഓരോ രാശിയെയും 8 കക്ഷ്യകളായി (3°45' വീതം) തിരിക്കുന്ന സൂക്ഷ്മ സമയനിർണ്ണയം. ഗോചാര ഗ്രഹം തന്റെ BAV-യിൽ ബിന്ദു നൽകിയ കക്ഷ്യയിലൂടെ കടക്കുമ്പോൾ മാത്രം ഫലപ്രദം.",
  "h_sat_kakshya": "ശനി ഗോചാര കക്ഷ്യകൾ",
  "h_jup_kakshya": "വ്യാഴ ഗോചാര കക്ഷ്യകൾ",
  "th_degree_range": "ഡിഗ്രി പരിധി",
  "th_lord": "നാഥൻ",
  "th_bav_bindu": "BAV ബിന്ദു",
  "th_result": "ഫലം",
  "h_shadbala": "ഷഡ്ബലം: ആറുവിധ ഗ്രഹബലം",
  "h_bhava_bala": "ഭാവബലം",
  "print_dialog_title": "പ്രിന്റ് അല്ലെങ്കിൽ PDF ആയി സേവ് ചെയ്യുക",
  "print_sections": "ഭാഗങ്ങൾ തിരഞ്ഞെടുക്കുക",
  "print_language": "ഭാഷ",
  "print_chart_style": "ചക്ര ശൈലി",
  "print_pdf_hint": "PDF ഉണ്ടാക്കാൻ, പ്രിന്റ് ജാലകത്തിൽ \"Save as PDF\" തിരഞ്ഞെടുക്കുക.",
  "cancel": "റദ്ദാക്കുക",
  "print_now": "പ്രിന്റ് / PDF",
  "navamsa_table": "നവാംശ (D9) പട്ടിക",
  "navamsa_table_sub": "ഓരോ ഗ്രഹത്തിന്റെയും നവാംശ രാശി, നാഥൻ, അവിടത്തെ ബലസ്ഥിതി, വർഗ്ഗോത്തമം, പുഷ്കര നവാംശം",
  "th_rasi": "രാശി",
  "th_navamsa": "നവാംശം",
  "th_amsa": "അംശം",
  "th_navamsa_lord": "നവാംശ നാഥൻ",
  "th_d9_dignity": "D9-ലെ ബലസ്ഥിതി",
  "th_notes": "കുറിപ്പ്",
  "shodasavarga_table": "ഷോഡശവർഗ്ഗ പട്ടിക",
  "shodasavarga_sub": "16 വർഗ്ഗ ചക്രങ്ങളിലും ഓരോ ഗ്രഹത്തിന്റെയും രാശി; രാശിചക്രത്തിലെ രാശി ആവർത്തിക്കുന്നിടം എടുത്തുകാട്ടിയിരിക്കുന്നു.",
  "muhurtham_title": "മുഹൂർത്തം കണ്ടെത്തൽ",
  "muhurtham_sub": "പരമ്പരാഗത മുഹൂർത്ത നിയമപ്രകാരമുള്ള പകൽ സമയങ്ങൾ: കാര്യത്തിനുള്ള നക്ഷത്രങ്ങൾ, നല്ല ആഴ്ചദിവസവും തിഥിയും, സിദ്ധ/അമൃത യോഗം, ശുദ്ധമായ ലഗ്നം (എട്ടിൽ പാപനില്ല, ചന്ദ്രൻ 6, 8, 12-ൽ ഇല്ല), ദോഷയോഗങ്ങൾ, വിഷ്ടി കരണം, രാഹുകാലം, യമഗണ്ഡം, ഗുളികൻ ഒഴിവാക്കി. ജാതകം ലോഡ് ചെയ്താൽ താരാബലവും ചന്ദ്രബലവും നോക്കി ചന്ദ്രാഷ്ടമ ദിവസങ്ങൾ ഒഴിവാക്കും.",
  "mh_marriage": "വിവാഹം",
  "mh_griha": "ഗൃഹപ്രവേശം",
  "mh_business": "സ്ഥാപനം തുടങ്ങൽ",
  "mh_vehicle": "വാഹനം വാങ്ങൽ",
  "mh_general": "ഏതു ശുഭകാര്യവും",
  "mh_30": "അടുത്ത 30 ദിവസം",
  "mh_60": "അടുത്ത 60 ദിവസം",
  "mh_90": "അടുത്ത 90 ദിവസം",
  "mh_find": "മുഹൂർത്തങ്ങൾ കണ്ടെത്തുക",
  "mh_note": "പ്രസിദ്ധീകരിച്ച പഞ്ചാംഗങ്ങൾ ലഗ്നവും പ്രാദേശിക ആചാരങ്ങളും നോക്കുന്നു; അന്തിമ സമയം കുടുംബ ജ്യോത്സ്യനുമായി ഉറപ്പാക്കുക.",
  "h_sudarshana": "സുദർശന ചക്രം",
  "pill_sudarshana": "ലഗ്നം · ചന്ദ്രൻ · സൂര്യൻ",
  "th_from_lagna": "ലഗ്നത്തിൽ നിന്ന്",
  "th_from_moon": "ചന്ദ്രനിൽ നിന്ന്",
  "th_from_sun": "സൂര്യനിൽ നിന്ന്",
  "h_vimsopaka": "വിംശോപക ബലവും വർഗ്ഗഭേദവും",
  "pill_vimsopaka": "20-ൽ",
  "p_vimsopaka": "ഷഡ്വർഗ്ഗ, സപ്തവർഗ്ഗ, ദശവർഗ്ഗ, ഷോഡശവർഗ്ഗ രീതികളിലെ ബലസ്ഥിതിയിൽ നിന്നുള്ള ബലം. രണ്ടോ അതിലധികമോ വർഗ്ഗങ്ങളിൽ സ്വക്ഷേത്രം, ഉച്ചം അല്ലെങ്കിൽ മൂലത്രികോണത്തിൽ നിൽക്കുന്ന ഗ്രഹത്തിന് വർഗ്ഗഭേദ പദവി.",
  "th_shadvarga": "ഷഡ്വർഗ്ഗം",
  "th_saptavarga": "സപ്തവർഗ്ഗം",
  "th_dasavarga": "ദശവർഗ്ഗം",
  "th_shodasavarga": "ഷോഡശവർഗ്ഗം",
  "pill_bhava_bala": "കുറഞ്ഞത് 7 രൂപ",
  "p_bhava_bala": "ഓരോ ശ്രീപതി ഭാവത്തിന്റെയും ബലം: ഭാവനാഥന്റെ ഷഡ്ബലം, ദിഗ്ബലം, ഭാവമധ്യത്തിലെ ദൃഷ്ടികൾ.",
  "th_bhava": "ഭാവം",
  "th_adhipati": "നാഥന്റെ ബലം",
  "th_dig": "ദിക്ക്",
  "th_drishti": "ദൃഷ്ടി",
  "th_rupas": "രൂപ",
  "th_rank": "സ്ഥാനം",
  "pill_shadbala": "പരമ്പരാഗത ഗണിത ബലം",
  "dominant_planet": "പ്രബല ഗ്രഹം (ആത്മബലം)",
  "karmic_vulnerability": "ദുർബല ഗ്രഹം (വളർച്ചയുടെ മേഖല)",
  "h_kp": "കൃഷ്ണമൂർത്തി പദ്ധതി (കെ.പി.) ഉപനാഥ വിശകലനം",
  "pill_kp": "പ്രൊഫ. കെ.എസ്. കൃഷ്ണമൂർത്തി 249 വിഭാഗങ്ങൾ",
  "p_kp": "കെ.പി. രീതി 27 നക്ഷത്രങ്ങളെയും വിംശോത്തരി അനുപാതത്തിൽ 9 അസമ ഉപവിഭാഗങ്ങളായി തിരിച്ച് ജീവിതഫലങ്ങൾ സൂക്ഷ്മമായി കണ്ടെത്തുന്നു.",
  "h_kp_cuspal": "ഭാവാരംഭ ഉപനാഥ ഫലങ്ങൾ",
  "h_kp_cusps": "12 കെ.പി. പ്ലാസിഡസ് ഭാവാരംഭങ്ങൾ",
  "th_cusp": "ഭാവാരംഭം",
  "th_degree": "ഡിഗ്രി",
  "th_sign": "രാശി",
  "th_sign_lord": "രാശിനാഥൻ",
  "th_star_lord": "നക്ഷത്രനാഥൻ",
  "th_sub_lord": "ഉപനാഥൻ",
  "th_kp_house": "ഭാവം",
  "th_significations": "സൂചിപ്പിക്കുന്ന ഭാവങ്ങൾ",
  "h_kp_planets": "9 ഗ്രഹങ്ങളുടെ കെ.പി. സ്ഥാനങ്ങൾ",
  "h_bnn": "ഭൃഗു നന്ദി നാഡി സൂത്രങ്ങൾ",
  "pill_bnn": "ഭൃഗു മഹർഷി പാരമ്പര്യം",
  "h_bnn_combos": "കണ്ടെത്തിയ നാഡി യോഗങ്ങളും ജീവിതപാഠങ്ങളും",
  "h_avasthas": "ഗ്രഹ അവസ്ഥകൾ",
  "pill_avasthas": "ബാലാദി, ജാഗ്രദാദി അവസ്ഥകൾ",
  "p_avasthas": "ഗ്രഹങ്ങൾ അവയുടെ പ്രായാവസ്ഥ (ബാല, കുമാര, യുവ, വൃദ്ധ, മൃത), ബോധാവസ്ഥ (ജാഗ്രത്, സ്വപ്നം, സുഷുപ്തി) അനുസരിച്ച് ഫലം നൽകുന്നു; വാഗ്ദാനം ചെയ്ത ഫലത്തിന്റെ എത്ര ശതമാനം ലഭിക്കുമെന്ന് ഇത് കാണിക്കുന്നു.",
  "h_pada": "ജന്മനക്ഷത്ര പാദ ഫലം",
  "birth_star_pada": "ജന്മനക്ഷത്രവും പാദവും",
  "navamsa_sign_lord": "നവാംശ രാശിയും നാഥനും",
  "h_sahams": "സഹമങ്ങൾ (താജിക)",
  "p_sahams": "ലഗ്നം, സൂര്യൻ, ചന്ദ്രൻ, ഗ്രഹദൂരങ്ങൾ എന്നിവയിൽ നിന്ന് കണക്കാക്കുന്ന സൂക്ഷ്മ ബിന്ദുക്കൾ: ഭാഗ്യം, വിദ്യ, വിവാഹം, തൊഴിൽ, ആരോഗ്യം.",
  "h_match_candidates": "പൊരുത്തത്തിനുള്ള വ്യക്തികളെ തിരഞ്ഞെടുക്കുക",
  "h_bride": "വധു (നക്ഷത്രവും കൂറും)",
  "h_groom": "വരൻ (നക്ഷത്രവും കൂറും)",
  "label_saved_profile": "സൂക്ഷിച്ച ജാതകം (ഐച്ഛികം)",
  "label_nakshatra": "നക്ഷത്രം (ജന്മനക്ഷത്രം)",
  "label_rasi": "കൂറ് (ചന്ദ്ര രാശി)",
  "btn_calc_match": "പൊരുത്തം കണക്കാക്കുക",
  "of_36_gunas": "/ 36 ഗുണങ്ങൾ",
  "final_verdict": "അന്തിമ വിധി",
  "h_10_poruthams": "10 ദക്ഷിണേന്ത്യൻ പൊരുത്തങ്ങൾ",
  "th_porutham": "പൊരുത്തം",
  "th_significance": "പ്രാധാന്യം",
  "th_status": "സ്ഥിതി",
  "th_points": "പോയിന്റ്",
  "h_ashta_koota": "ഉത്തരേന്ത്യൻ അഷ്ടകൂടം (36 ഗുണങ്ങൾ)",
  "footer_calc": "സ്വിസ് എഫെമെറിസ് (AGPL) ഉപയോഗിച്ച് കണക്കാക്കിയത്",
  "footer_private": "സ്വകാര്യം, ഓഫ്‌ലൈനിലും പ്രവർത്തിക്കും · ജാതകങ്ങൾ നിങ്ങളുടെ കമ്പ്യൂട്ടറിൽ തന്നെ",
  "gem_primary_label": "ജീവരത്നം (ലഗ്നാധിപൻ):",
  "gem_fortune_label": "ഭാഗ്യരത്നം (ഒൻപതാം ഭാവാധിപൻ):",
  "gem_metal_label": "നിർദ്ദേശിച്ച ലോഹം:",
  "gem_finger_label": "അണിയേണ്ട വിരൽ:",
  "gem_day_label": "ശുഭ ദിവസം:",
  "luck_numbers_label": "ഭാഗ്യ സംഖ്യകൾ:",
  "luck_days_label": "ഭാഗ്യ ദിവസങ്ങൾ:",
  "luck_colors_label": "അനുകൂല നിറങ്ങൾ:",
  "luck_deities_label": "ആരാധനാ ദേവതകൾ:",
  "h_jaimini": "ജൈമിനി മഹർഷിയുടെ 7 ചര കാരകങ്ങളും കാരകാംശവും",
  "h_double_transit": "കെ.എൻ. റാവുവിന്റെ ഇരട്ട ഗോചാര സമയനിർണ്ണയം",
  "ph_profile_search": "പേര്, സ്ഥലം, കൂറ്, നക്ഷത്രം എന്നിവയാൽ തിരയുക...",
  "title_profiles_new": "ജനന ഫോമിൽ പുതിയ വ്യക്തിയെ നൽകുക",
  "title_export_json": "എല്ലാ ജാതകങ്ങളും JSON ഫയലായി എടുക്കുക",
  "title_import_json": "JSON ബാക്കപ്പിൽ നിന്ന് ജാതകങ്ങൾ ചേർക്കുക",
  "title_clear_all": "സൂക്ഷിച്ച എല്ലാ ജാതകങ്ങളും മായ്ക്കുക",
  "footer_tagline": "ആധുനിക കൃത്യതയുള്ള വൈദിക ജ്യോതിഷം"
};

const ML_TERMS = {
  "Aries": "മേടം",
  "Taurus": "ഇടവം",
  "Gemini": "മിഥുനം",
  "Cancer": "കർക്കടകം",
  "Leo": "ചിങ്ങം",
  "Virgo": "കന്നി",
  "Libra": "തുലാം",
  "Scorpio": "വൃശ്ചികം",
  "Sagittarius": "ധനു",
  "Capricorn": "മകരം",
  "Aquarius": "കുംഭം",
  "Pisces": "മീനം",
  "Ashwini": "അശ്വതി",
  "Bharani": "ഭരണി",
  "Krittika": "കാർത്തിക",
  "Rohini": "രോഹിണി",
  "Mrigashira": "മകയിരം",
  "Ardra": "തിരുവാതിര",
  "Punarvasu": "പുണർതം",
  "Pushya": "പൂയം",
  "Ashlesha": "ആയില്യം",
  "Magha": "മകം",
  "Purva Phalguni": "പൂരം",
  "Uttara Phalguni": "ഉത്രം",
  "Hasta": "അത്തം",
  "Chitra": "ചിത്തിര",
  "Swati": "ചോതി",
  "Vishakha": "വിശാഖം",
  "Anuradha": "അനിഴം",
  "Jyeshtha": "തൃക്കേട്ട",
  "Mula": "മൂലം",
  "Purva Ashadha": "പൂരാടം",
  "Uttara Ashadha": "ഉത്രാടം",
  "Shravana": "തിരുവോണം",
  "Dhanishtha": "അവിട്ടം",
  "Shatabhisha": "ചതയം",
  "Purva Bhadrapada": "പൂരുരുട്ടാതി",
  "Uttara Bhadrapada": "ഉത്രട്ടാതി",
  "Revati": "രേവതി",
  "Abhijit": "അഭിജിത്",
  "Sun": "സൂര്യൻ",
  "Moon": "ചന്ദ്രൻ",
  "Mars": "ചൊവ്വ",
  "Mercury": "ബുധൻ",
  "Jupiter": "വ്യാഴം",
  "Venus": "ശുക്രൻ",
  "Saturn": "ശനി",
  "Rahu": "രാഹു",
  "Ketu": "കേതു",
  "Ascendant": "ലഗ്നം",
  "Lagna": "ലഗ്നം",
  "Mandi": "മാന്ദി",
  "Sunday": "ഞായർ",
  "Monday": "തിങ്കൾ",
  "Tuesday": "ചൊവ്വ",
  "Wednesday": "ബുധൻ",
  "Thursday": "വ്യാഴം",
  "Friday": "വെള്ളി",
  "Saturday": "ശനി",
  "Prathama": "പ്രഥമ",
  "Dwitiya": "ദ്വിതീയ",
  "Tritiya": "തൃതീയ",
  "Chaturthi": "ചതുർത്ഥി",
  "Panchami": "പഞ്ചമി",
  "Shashthi": "ഷഷ്ഠി",
  "Saptami": "സപ്തമി",
  "Ashtami": "അഷ്ടമി",
  "Navami": "നവമി",
  "Dashami": "ദശമി",
  "Ekadashi": "ഏകാദശി",
  "Dwadashi": "ദ്വാദശി",
  "Trayodashi": "ത്രയോദശി",
  "Chaturdashi": "ചതുർദശി",
  "Purnima": "പൗർണ്ണമി",
  "Amavasya": "അമാവാസി",
  "Shukla": "ശുക്ലപക്ഷം",
  "Krishna": "കൃഷ്ണപക്ഷം",
  "Vishkambha": "വിഷ്കംഭം",
  "Priti": "പ്രീതി",
  "Ayushman": "ആയുഷ്മാൻ",
  "Saubhagya": "സൗഭാഗ്യം",
  "Shobhana": "ശോഭനം",
  "Atiganda": "അതിഗണ്ഡം",
  "Sukarma": "സുകർമ്മം",
  "Dhriti": "ധൃതി",
  "Shula": "ശൂലം",
  "Ganda": "ഗണ്ഡം",
  "Vriddhi": "വൃദ്ധി",
  "Dhruva": "ധ്രുവം",
  "Vyaghata": "വ്യാഘാതം",
  "Harshana": "ഹർഷണം",
  "Vajra": "വജ്രം",
  "Siddhi": "സിദ്ധി",
  "Vyatipata": "വ്യതീപാതം",
  "Variyan": "വരീയാൻ",
  "Parigha": "പരിഘം",
  "Shiva": "ശിവം",
  "Siddha": "സിദ്ധം",
  "Sadhya": "സാധ്യം",
  "Shubha": "ശുഭം",
  "Brahma": "ബ്രഹ്മം",
  "Indra": "ഐന്ദ്രം",
  "Vaidhriti": "വൈധൃതി",
  "Bava": "ബവം",
  "Balava": "ബാലവം",
  "Kaulava": "കൗലവം",
  "Taitila": "തൈതിലം",
  "Gara": "ഗരജം",
  "Vanija": "വണിജം",
  "Vishti": "വിഷ്ടി",
  "Shakuni": "ശകുനി",
  "Chatushpada": "ചതുഷ്പാദം",
  "Naga": "നാഗം",
  "Kimstughna": "കിംസ്തുഘ്നം",
  "Chithirai": "മേടം",
  "Vaikasi": "ഇടവം",
  "Aani": "മിഥുനം",
  "Aadi": "കർക്കടകം",
  "Aavani": "ചിങ്ങം",
  "Purattasi": "കന്നി",
  "Aippasi": "തുലാം",
  "Karthigai": "വൃശ്ചികം",
  "Margazhi": "ധനു",
  "Thai": "മകരം",
  "Maasi": "കുംഭം",
  "Panguni": "മീനം",
  "Exalted": "ഉച്ചം",
  "Own Sign": "സ്വക്ഷേത്രം",
  "Moolatrikona": "മൂലത്രികോണം",
  "Great Friend": "അതിമിത്രം",
  "Friend": "മിത്രം",
  "Neutral": "സമം",
  "Enemy": "ശത്രു",
  "Great Enemy": "അതിശത്രു",
  "Debilitated": "നീചം",
  "Favourable": "അനുകൂലം",
  "Mixed": "സമ്മിശ്രം",
  "Needs care": "ശ്രദ്ധ വേണം",
  "Strong": "ബലവാൻ",
  "Moderate": "മധ്യമം",
  "Weak": "ദുർബലം",
  "Siddha Yogam": "സിദ്ധയോഗം",
  "Amirtha Yogam": "അമൃതയോഗം",
  "Marana Yogam": "മരണയോഗം",
  "Prabalarishta Yogam": "പ്രബലാരിഷ്ടയോഗം",
  " Checked against your birth star and Moon sign.": " നിങ്ങളുടെ ജന്മനക്ഷത്രവും കൂറും നോക്കി പരിശോധിച്ചു.",
  " · now": " · ഇപ്പോൾ",
  "0 Bindu": "0 ബിന്ദു",
  "1 Bindu": "1 ബിന്ദു",
  "10 Poruthams": "10 പൊരുത്തങ്ങൾ",
  "10th lord": "പത്താം ഭാവാധിപൻ",
  "ACTIVE": "നടക്കുന്നു",
  "Active": "നടക്കുന്നു",
  "After Trikona and Ekadhipatya reduction, with the Pindas": "ത്രികോണ, ഏകാധിപത്യ ശോധനയ്ക്ക് ശേഷം, പിണ്ഡങ്ങളോടെ",
  "Amsa": "അംശം",
  "Antardasa": "അന്തർദശ",
  "Ashta Koota (36 Gunas)": "അഷ്ടകൂടം (36 ഗുണങ്ങൾ)",
  "Ashtottari Dasa": "അഷ്ടോത്തരി ദശ",
  "Auspicious": "ശുഭം",
  "Average": "ശരാശരി",
  "Avoid": "ഒഴിവാക്കുക",
  "Ayanamsa": "അയനാംശം",
  "Begins (sandhi)": "തുടക്കം (സന്ധി)",
  "Bhava": "ഭാവം",
  "Bhava Bala": "ഭാവബലം",
  "Bhava Bala (rupas)": "ഭാവബലം (രൂപ)",
  "Bhava Bala (rupas; minimum 7)": "ഭാവബലം (രൂപ; കുറഞ്ഞത് 7)",
  "Bhava Chakra (Sripati)": "ഭാവചക്രം (ശ്രീപതി)",
  "Bhinnashtakavarga and Sarvashtakavarga": "ഭിന്നാഷ്ടകവർഗ്ഗവും സർവ്വാഷ്ടകവർഗ്ഗവും",
  "Bhukti": "അപഹാരം",
  "Birth Star / Nakshatra": "ജന്മനക്ഷത്രം",
  "Birth data": "ജനന വിവരം",
  "Birth star and Lagna": "ജന്മനക്ഷത്രവും ലഗ്നവും",
  "Birth stars": "ജന്മനക്ഷത്രങ്ങൾ",
  "Bride": "വധു",
  "C": "മൗ",
  "Career (Karmajeeva & D-10)": "തൊഴിൽ (കർമ്മജീവം, D-10)",
  "Career and health": "തൊഴിലും ആരോഗ്യവും",
  "Chandrashtamam": "ചന്ദ്രാഷ്ടമം",
  "Cheshta": "ചേഷ്ട",
  "Chesta": "ചേഷ്ട",
  "Chevvai Dosham": "ചൊവ്വാ ദോഷം",
  "Choose at least one section.": "കുറഞ്ഞത് ഒരു ഭാഗം തിരഞ്ഞെടുക്കുക.",
  "Combust": "മൗഢ്യം",
  "Component breakdown (virupas)": "ഘടകങ്ങൾ (വിരൂപ)",
  "Cusp": "ഭാവാരംഭം",
  "Cuspal sub-lord verdicts": "ഭാവാരംഭ ഉപനാഥ ഫലങ്ങൾ",
  "Custom Location": "സ്വന്തം സ്ഥലം",
  "D-10 Lagna": "D-10 ലഗ്നം",
  "Dasa": "ദശ",
  "Dasa Sandhi": "ദശാസന്ധി",
  "Dasa balance at birth": "ജനനസമയ ദശാശിഷ്ടം",
  "Dasa-Bhukti forecast": "ദശാ-അപഹാര ഫലം",
  "Dasavarga": "ദശവർഗ്ഗം",
  "Date of birth": "ജനന തീയതി",
  "Day": "പകൽ",
  "Degree": "ഡിഗ്രി",
  "Dig": "ദിക്ക്",
  "Dignity": "ബലസ്ഥിതി",
  "Dignity in D9": "D9-ലെ ബലസ്ഥിതി",
  "Direct": "നേർഗതി",
  "Dosha": "ദോഷം",
  "Dosha Samyam": "ദോഷസാമ്യം",
  "Doshas": "ദോഷങ്ങൾ",
  "Drik": "ദൃക്ക്",
  "End": "അവസാനം",
  "Ends (sandhi)": "അവസാനം (സന്ധി)",
  "For marriage matching": "വിവാഹ പൊരുത്തത്തിന്",
  "From": "മുതൽ",
  "Gana · Yoni": "ഗണം · യോനി",
  "Generate a chart first.": "ആദ്യം ജാതകം തയ്യാറാക്കുക.",
  "Geolocation is not supported by your browser.": "നിങ്ങളുടെ ബ്രൗസർ സ്ഥലനിർണ്ണയം പിന്തുണയ്ക്കുന്നില്ല.",
  "Graha": "ഗ്രഹം",
  "Graha P.": "ഗ്രഹ പി.",
  "Graha Pinda": "ഗ്രഹ പിണ്ഡം",
  "Grahas": "ഗ്രഹങ്ങൾ",
  "Groom": "വരൻ",
  "Guna": "ഗുണം",
  "Horoscope compatibility calculated": "ജാതക പൊരുത്തം കണക്കാക്കി",
  "House": "ഭാവം",
  "Import error": "ചേർക്കുന്നതിൽ പിശക്",
  "Inauspicious": "അശുഭം",
  "Ishta": "ഇഷ്ട",
  "Ishta Phala": "ഇഷ്ടഫലം",
  "Jaimini Chara Dasa": "ജൈമിനി ചര ദശ",
  "Jathaga Kurippu": "ജാതകക്കുറിപ്പ്",
  "JoRoScope Muhurthams": "ജോറോസ്കോപ്പ് മുഹൂർത്തങ്ങൾ",
  "JoRoScope Tamil calendar": "ജോറോസ്കോപ്പ് കലണ്ടർ",
  "Kaal Sarp Dosham": "കാളസർപ്പ ദോഷം",
  "Kaala": "കാലം",
  "Karmajeeva graha": "കർമ്മജീവ ഗ്രഹം",
  "Kashta": "കഷ്ട",
  "Kashta Phala": "കഷ്ടഫലം",
  "Krishnamurti": "കൃഷ്ണമൂർത്തി",
  "Latitude · Longitude": "അക്ഷാംശം · രേഖാംശം",
  "Live": "തത്സമയം",
  "Loading the detailed reading…": "വിശദ ഫലം ലോഡ് ചെയ്യുന്നു…",
  "Lord": "നാഥൻ",
  "Madhya": "മധ്യം",
  "Marriage Compatibility Report": "വിവാഹ പൊരുത്ത റിപ്പോർട്ട്",
  "Matching error": "പൊരുത്തത്തിൽ പിശക്",
  "Matter": "വിഷയം",
  "Meaning": "അർത്ഥം",
  "Moon Sign / Rasi": "കൂറ്",
  "Naisargika": "നൈസർഗ്ഗിക",
  "Nakshatra": "നക്ഷത്രം",
  "Nakshatra · Pada": "നക്ഷത്രം · പാദം",
  "Nalla Neram": "നല്ല നേരം",
  "Name": "പേര്",
  "Navamsa": "നവാംശം",
  "Navamsa (D9)": "നവാംശം (D9)",
  "Navamsa lord": "നവാംശ നാഥൻ",
  "Night": "രാത്രി",
  "No direct major aspects": "പ്രധാന ദൃഷ്ടികളില്ല",
  "No major classical yogas triggered under primary rules.": "പ്രധാന നിയമപ്രകാരം പ്രമുഖ യോഗങ്ങളില്ല.",
  "No major yoga found.": "പ്രധാന യോഗങ്ങളൊന്നുമില്ല.",
  "No observances this month.": "ഈ മാസം വ്രതദിനങ്ങളില്ല.",
  "No occupant planets": "ഗ്രഹങ്ങളില്ല",
  "No suitable day in this period; try a longer range.": "ഈ കാലയളവിൽ അനുയോജ്യ ദിവസമില്ല; കൂടുതൽ ദിവസം തിരഞ്ഞെടുക്കുക.",
  "No ✖": "ഇല്ല ✖",
  "Not Matched ✖": "പൊരുത്തമില്ല ✖",
  "Not Present": "ഇല്ല",
  "Not available for this chart.": "ഈ ജാതകത്തിന് ലഭ്യമല്ല.",
  "Not present": "ഇല്ല",
  "Notes": "കുറിപ്പ്",
  "Now": "ഇപ്പോൾ",
  "Pada": "പാദം",
  "Page": "പേജ്",
  "Panchanga Phala": "പഞ്ചാംഗ ഫലം",
  "Papa points (L / C / S)": "പാപ ബിന്ദുക്കൾ (ല / ച / ശു)",
  "Passed ✔": "പൊരുത്തമുണ്ട് ✔",
  "Place of birth": "ജനന സ്ഥലം",
  "Placidus cusps in the Krishnamurti ayanamsa": "കൃഷ്ണമൂർത്തി അയനാംശത്തിലെ പ്ലാസിഡസ് ഭാവാരംഭങ്ങൾ",
  "Planet": "ഗ്രഹം",
  "Points": "പോയിന്റ്",
  "Porutham": "പൊരുത്തം",
  "Position": "സ്ഥാനം",
  "Pratyantardasa Details": "പ്രത്യന്തർദശ വിവരങ്ങൾ",
  "Present": "ഉണ്ട്",
  "Present, cancelled": "ഉണ്ട്, പരിഹരിക്കപ്പെട്ടു",
  "Pushkara": "പുഷ്കരം",
  "Pushkara Navamsa": "പുഷ്കര നവാംശം",
  "Querying coordinates...": "സ്ഥാനം കണ്ടെത്തുന്നു...",
  "R": "വ",
  "Rahu-Ketu Dosham": "രാഹു-കേതു ദോഷം",
  "Rajju Dosha: Inauspicious (Same Rajju)": "രജ്ജു ദോഷം: അശുഭം (ഒരേ രജ്ജു)",
  "Rajju Match: Harmonious (Passed)": "രജ്ജു പൊരുത്തം: അനുകൂലം",
  "Rajju · Nadi": "രജ്ജു · നാഡി",
  "Rank": "സ്ഥാനം",
  "Rasi": "രാശി",
  "Rasi (D1)": "രാശി (D1)",
  "Rasi P.": "രാശി പി.",
  "Rasi Pinda": "രാശി പിണ്ഡം",
  "Ratio": "അനുപാതം",
  "Reason": "കാരണം",
  "Reckoned from": "കണക്കാക്കിയത്",
  "Report": "റിപ്പോർട്ട്",
  "Required": "ആവശ്യം",
  "Result": "ഫലം",
  "Retrograde (Rx)": "വക്രം",
  "Ruling planets at birth": "ജനനസമയത്തെ ഭരണ ഗ്രഹങ്ങൾ",
  "Rupas": "രൂപ",
  "SAV": "SAV",
  "SAV Bindus": "SAV ബിന്ദുക്കൾ",
  "Samyam": "സാമ്യം",
  "Saptavarga": "സപ്തവർഗ്ഗം",
  "Shadbala (virupas; totals in rupas)": "ഷഡ്ബലം (വിരൂപ; ആകെ രൂപയിൽ)",
  "Shadvarga": "ഷഡ്വർഗ്ഗം",
  "Shodasavarga": "ഷോഡശവർഗ്ഗം",
  "Shodasavarga table (bold: same sign as the Rasi)": "ഷോഡശവർഗ്ഗ പട്ടിക (കട്ടിയക്ഷരം: രാശിചക്രത്തിലെ അതേ രാശി)",
  "Sign lord": "രാശിനാഥൻ",
  "Significance": "പ്രാധാന്യം",
  "Signifies": "സൂചിപ്പിക്കുന്നത്",
  "Sodhya P.": "ശോധ്യ പി.",
  "Sodhya Pinda": "ശോധ്യ പിണ്ഡം",
  "Star lord": "നക്ഷത്രനാഥൻ",
  "Star · Pada": "നക്ഷത്രം · പാദം",
  "Start": "തുടക്കം",
  "Sthana": "സ്ഥാനം",
  "Storage error: please export profiles backup.": "സംഭരണ പിശക്: ജാതകങ്ങളുടെ ബാക്കപ്പ് എടുക്കുക.",
  "Sub lord": "ഉപനാഥൻ",
  "Sudarshana Chakra this year": "ഈ വർഷത്തെ സുദർശന ചക്രം",
  "Sunrise · Sunset": "സൂര്യോദയം · അസ്തമയം",
  "The file is not valid JSON.": "ഫയൽ ശരിയായ JSON അല്ല.",
  "The file is too large for a profile backup.": "ബാക്കപ്പിന് ഫയൽ വളരെ വലുതാണ്.",
  "The running Dasa": "നടപ്പുദശ",
  "The twelve Bhavas": "12 ഭാവങ്ങൾ",
  "Time of birth": "ജനന സമയം",
  "Time zone": "സമയമേഖല",
  "To": "വരെ",
  "Total": "ആകെ",
  "Transits (Gochara)": "ഗോചാരം",
  "Unnamed Chart": "പേരില്ലാത്ത ജാതകം",
  "Use as Boy in Horoscope Compatibility": "പൊരുത്തത്തിൽ വരനായി ഉപയോഗിക്കുക",
  "Use as Girl in Horoscope Compatibility": "പൊരുത്തത്തിൽ വധുവായി ഉപയോഗിക്കുക",
  "V": "വർ",
  "Vargottama": "വർഗ്ഗോത്തമം",
  "Verdict": "വിധി",
  "Vimsopaka Bala (out of 20) & Varga Bheda": "വിംശോപക ബലം (20-ൽ), വർഗ്ഗഭേദം",
  "Virupas": "വിരൂപ",
  "Weekday, Tithi, Yoga & Karana at Birth": "ജനനസമയത്തെ വാരം, തിഥി, യോഗം, കരണം",
  "Years": "വർഷം",
  "Yes ✔": "ഉണ്ട് ✔",
  "Yoga": "യോഗം",
  "Yogas": "യോഗങ്ങൾ",
  "Yogini": "യോഗിനി",
  "Yogini Dasa": "യോഗിനി ദശ",
  "dasa": "ദശ",
  "dasa supports": "ദശ പിന്തുണയ്ക്കുന്നു",
  "from birth": "ജനനം മുതൽ",
  "rupas": "രൂപ",
  "Special reports": "പ്രത്യേക റിപ്പോർട്ടുകൾ",
  "Traditional Jathagam": "പരമ്പരാഗത ജാതകം",
  "Detailed Horoscope": "വിശദ ജാതകം",
  "Complete Report": "സമ്പൂർണ്ണ റിപ്പോർട്ട്",
  "Horoscope": "ജാതകം",
  "Dark": "ഇരുണ്ട",
  "Ruby": "മാണിക്യം",
  "Natural Pearl": "മുത്ത്",
  "Red Coral": "പവിഴം",
  "Emerald": "മരതകം",
  "Yellow Sapphire": "പുഷ്യരാഗം",
  "Diamond": "വജ്രം",
  "Blue Sapphire": "ഇന്ദ്രനീലം",
  "Gold": "സ്വർണ്ണം",
  "Copper": "ചെമ്പ്",
  "Platinum": "പ്ലാറ്റിനം",
  "Silver": "വെള്ളി",
  "Iron": "ഇരുമ്പ്",
  "Ring Finger": "മോതിരവിരൽ",
  "Middle Finger": "നടുവിരൽ",
  "Little Finger": "ചെറുവിരൽ",
  "Index Finger": "ചൂണ്ടുവിരൽ",
  "Middle / Little Finger": "നടുവിരൽ / ചെറുവിരൽ",
  "Little / Ring Finger": "ചെറുവിരൽ / മോതിരവിരൽ",
  "Little / Index Finger": "ചെറുവിരൽ / ചൂണ്ടുവിരൽ",
  "Index / Ring Finger": "ചൂണ്ടുവിരൽ / മോതിരവിരൽ",
  "Bright Red": "തിളങ്ങുന്ന ചുവപ്പ്",
  "Crimson": "കടുംചുവപ്പ്",
  "Golden Yellow": "സ്വർണ്ണ മഞ്ഞ",
  "Diamond White": "വജ്രവെള്ള",
  "Pale Pink": "ഇളം പിങ്ക്",
  "Cream": "ക്രീം",
  "Emerald Green": "മരതകപ്പച്ച",
  "Pastel Shades": "മൃദുവർണ്ണങ്ങൾ",
  "Pearl White": "മുത്തുവെള്ള",
  "Deep Gold": "കടുംസ്വർണ്ണം",
  "Orange": "ഓറഞ്ച്",
  "Ruby Red": "മാണിക്യച്ചുവപ്പ്",
  "Parrot Green": "തത്തപ്പച്ച",
  "Turquoise": "നീലപ്പച്ച",
  "Pure White": "ശുദ്ധവെള്ള",
  "Rose Pink": "റോസ്",
  "Silk Blue": "പട്ടുനീല",
  "Scarlet Red": "ചെഞ്ചുവപ്പ്",
  "Rust": "തുരുമ്പ് നിറം",
  "Amber": "ആംബർ",
  "Bright Yellow": "തിളങ്ങുന്ന മഞ്ഞ",
  "Saffron": "കാവി",
  "Royal Blue": "രാജനീല",
  "Navy": "കടുംനീല",
  "Steel Grey": "ഉരുക്കുചാര",
  "Electric Blue": "ഇലക്ട്രിക് നീല",
  "Violet": "വയലറ്റ്",
  "Indigo": "ഇൻഡിഗോ",
  "Pale Yellow": "ഇളംമഞ്ഞ",
  "Golden Amber": "സ്വർണ്ണ ആംബർ",
  "Sea Green": "കടൽപ്പച്ച",
  "Sign": "രാശി",
  "Pancha-vargeeya Bala": "പഞ്ചവർഗ്ഗീയ ബലം",
  "Value": "മൂല്യം",
  "Ruling graha": "അധിപ ഗ്രഹം",
  "Favourable day": "അനുകൂല ദിവസം",
  "Number": "സംഖ്യ",
  "Temple": "ക്ഷേത്രം",
  "Deity": "ദേവത",
  "Japa count": "ജപ സംഖ്യ",
  "House from Moon": "കൂറിൽ നിന്നുള്ള ഭാവം",
  "Bindus": "ബിന്ദുക്കൾ",
  "Office": "പദവി",
  "Bala": "ബലം",
  "Dasa / Bhukti": "ദശ / അപഹാരം",
  "Strength": "ബലം",
  "strong": "ബലവത്ത്",
  "moderate": "മധ്യമം",
  "Star": "നക്ഷത്രം",
  "Vedha by": "വേധം",
  "Count": "എണ്ണം",
  "Ring": "വലയം",
  "Motion": "ഗതി",
  "Factor": "ഘടകം",
  "Effect": "ഫലം",
  "helps": "അനുകൂലം",
  "hinders": "പ്രതികൂലം",
  "neutral": "സമം",
  "Time range": "സമയ പരിധി",
  "Best time": "മികച്ച സമയം",
  "Score": "സ്കോർ",
  "favourable": "അനുകൂലം",
  "unfavourable": "പ്രതികൂലം",
  "mixed": "സമ്മിശ്രം",
  "troubled": "ബാധിതം",
  "supported": "പിന്തുണ",
  "clear": "തെളിഞ്ഞത്",
  "entering": "പ്രവേശിക്കുന്നു",
  "leaving": "പുറത്തുപോകുന്നു",
  "at the centre": "മധ്യത്തിൽ",
  "running": "നടക്കുന്നു",
  "Birth sign": "ജന്മരാശി",
  "Janma": "ജന്മ",
  "Karma": "കർമ്മ",
  "Sanghatika": "സാംഘാതിക",
  "Samudaya": "സാമുദായിക",
  "Vainashika": "വൈനാശിക",
  "Manasa": "മാനസ",
  "Muhurtham": "മുഹൂർത്തം",
  "Observances": "വ്രതങ്ങൾ",
  "Light": "തെളിഞ്ഞ",
  "Complete Horoscope Report": "സമ്പൂർണ്ണ ജാതക റിപ്പോർട്ട്",
  "Hora": "ഹോര",
  "Drekkana": "ദ്രേക്കാണം",
  "Chaturthamsa": "ചതുർത്ഥാംശം",
  "Saptamsa": "സപ്താംശം",
  "Dasamsa": "ദശാംശം",
  "Dwadasamsa": "ദ്വാദശാംശം",
  "Shodasamsa": "ഷോഡശാംശം",
  "Vimsamsa": "വിംശാംശം",
  "Chaturvimsamsa": "ചതുർവിംശാംശം",
  "Saptavimsamsa": "സപ്തവിംശാംശം",
  "Trimsamsa": "ത്രിംശാംശം",
  "Khavedamsa": "ഖവേദാംശം",
  "Akshavedamsa": "അക്ഷവേദാംശം",
  "Shashtiamsa": "ഷഷ്ട്യംശം",
  "Bhava Chakra": "ഭാവചക്രം"
};

// Graha abbreviations for the charts
const ML_SHORT = { Sun: 'സൂ', Moon: 'ച', Mars: 'ചൊ', Mercury: 'ബു', Jupiter: 'വ്യാ', Venus: 'ശു', Saturn: 'ശ', Rahu: 'രാ', Ketu: 'കേ',
  Ascendant: 'ല', Mandi: 'മാ' };

// Malayalam the server wrote for its readings, keyed by their English text. Server objects carry
// Malayalam as a "_ml" field beside "_en" and "_ta" (or "ml" beside "en" and "ta"); learnMalayalam()
// collects them from each response so that every place showing the English text can show it.
const ML_DYNAMIC = new Map();

function learnMalayalam(value) {
  if (Array.isArray(value)) {
    value.forEach(learnMalayalam);
    return;
  }
  if (!value || typeof value !== 'object') return;
  if (typeof value.en === 'string' && typeof value.ml === 'string') ML_DYNAMIC.set(value.en.trim(), value.ml);
  for (const [key, ml] of Object.entries(value)) {
    if (key.endsWith('_ml')) {
      // The English beside it is "name_en" or plain "name"
      const base = key.slice(0, -3);
      const en = value[base + '_en'] ?? value[base];
      if (typeof en === 'string' && typeof ml === 'string') ML_DYNAMIC.set(en.trim(), ml);
      else if (Array.isArray(en) && Array.isArray(ml)) en.forEach((item, i) => {
        if (typeof item === 'string' && typeof ml[i] === 'string') ML_DYNAMIC.set(item.trim(), ml[i]);
      });
    } else if (ml && typeof ml === 'object') {
      learnMalayalam(ml);
    }
  }
}

// Malayalam for a term or a list of terms; anything not known stays as it is
function mlTerm(value) {
  if (Array.isArray(value)) return value.map(mlTerm);
  if (typeof value !== 'string') return value;
  const key = value.trim();
  const known = ML_DYNAMIC.get(key) ?? ML_TERMS[value] ?? ML_TERMS[key];
  if (known !== undefined) return known;
  return key.length <= 80 ? mlTermsInText(value) : value;
}

// Whole-word Malayalam for known terms inside short labels such as "Purva Ashadha (Pada 2)"
let mlTermPattern = null;
function mlTermsInText(text) {
  if (!mlTermPattern) {
    const keys = Object.keys(ML_TERMS).filter(k => /^[A-Za-z][A-Za-z .'-]*[A-Za-z]$/.test(k)).sort((a, b) => b.length - a.length);
    mlTermPattern = new RegExp(`(?<![A-Za-z])(${keys.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})(?![A-Za-z])`, 'g');
  }
  return text.replace(mlTermPattern, m => ML_TERMS[m]);
}

// Translate the text nodes under a root: whole known terms, and known words in short labels.
// Long sentences (readings from the server) are left as they are rather than half-translated.
function translateTree(root) {
  if (!root) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => {
    if (node.parentElement?.closest('[data-keep-en]')) return;  // an English second label kept on purpose
    const raw = node.nodeValue;
    const key = raw.trim();
    if (!key) return;
    if (ML_DYNAMIC.has(key)) node.nodeValue = raw.replace(key, ML_DYNAMIC.get(key));
    else if (ML_TERMS[key] !== undefined) node.nodeValue = raw.replace(key, ML_TERMS[key]);
    else if (key.length <= 80 && /[A-Za-z]{2}/.test(key)) node.nodeValue = mlTermsInText(raw);
  });
}
